export enum CUSTOM_REQUEST_STATUS {
  PENDING = 'PENDING',
  REVIEWED = 'REVIEWED',
  QUOTED = 'QUOTED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export default CUSTOM_REQUEST_STATUS;
